sudo: required

services:
  - docker

branches:

  only:
    - master

addons:
  ssh_known_hosts: elorigendelaespecie.com:22

before_install:

  - openssl aes-256-cbc -K $encrypted_c37dc1143c88_key -iv $encrypted_c37dc1143c88_iv -in .travis/inuki2.pem.enc -out ./deploy_key -d

  # bajando el cliente de heroku y login
  #- wget -qO- https://toolbelt.heroku.com/install.sh | sh

  # login al docker registries de heroku (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com


script:

  - docker build -t inukisoft/python-microtest .
  - docker tag python-microtest inukisoft/python-microtest
  - docker push inukisoft/python-microtest

  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key ubuntu@elorigendelaespecie.com pwd




#  - docker stack deploy --compose-file docker-compose.yml stack-python

#  - docker run -d inukisoft/python-microtest $project
#  - docker tag inukisoft/python-microtest registry.heroku.com/$HEROKU_APP_NAME/web
#  - docker push registry.heroku.com/$HEROKU_APP_NAME/web


after_script:

  - docker images

before_deploy:


deploy:
#  provider: script
#  script: 
#    docker push inukisoft/python-microtest;
#    docker push registry.heroku.com/$HEROKU_APP_NAME/web;    
#    heroku container:release web --app $HEROKU_APP_NAME
#  on:
#    branch: master  